remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap


title: Tech-Notes
description: Blog de notas sobre Software, Ingeniería y Tecnología
